#include <stddef.h>
#include "edsa_error_codes.h"

//gets corresponding error string from code
size_t edsa_get_error_string(size_t error, char **str)
{
	switch(error){
		case EDSA_SUCCESS:
			*str = "EDSA_SUCCESS";
			break;
		case EDSA_STACK_INIT_STACK_MALLOC_FAILED:
			*str = "EDSA_STACK_INIT_STACK_MALLOC_FAILED";
			break;
		case EDSA_STACK_INIT_STACK_METADATA_MALLOC_FAILED:
			*str = "EDSA_STACK_INIT_STACK_METADATA_MALLOC_FAILED";
			break;
		case EDSA_STACK_INIT_STACK_SIZE_MULTIPLICATION_OVERFLOW:
			*str = "EDSA_STACK_INIT_STACK_SIZE_MULTIPLICATION_OVERFLOW";
			break;
		case EDSA_STACK_INIT_ZERO_ALLOC_SIZE:
			*str = "EDSA_STACK_INIT_ZERO_ALLOC_SIZE";
			break;
		case EDSA_STACK_POP_STACK_EMPTY:
			*str = "EDSA_STACK_POP_STACK_EMPTY";
			break;
		case EDSA_STACK_PUSH_STACK_FULL:
			*str = "EDSA_STACK_PUSH_STACK_FULL";
			break;
		case EDSA_STACK_REALLOC_FAILED:
			*str = "EDSA_STACK_REALLOC_FAILED";
			break;
		case EDSA_EXPARR_INIT_MALLOC_FAILED:
			*str = "EDSA_EXPARR_INIT_MALLOC_FAILED";
			break;
		case EDSA_EXPARR_INIT_ZERO_ALLOC_SIZE:
			*str = "EDSA_EXPARR_INIT_ZERO_ALLOC_SIZE";
			break;
		case EDSA_EXPARR_INIT_MULTIPLICATION_OVERFLOW:
			*str = "EDSA_EXPARR_INIT_MULTIPLICATION_OVERFLOW";
			break;
		case EDSA_EXPARR_INS_INDEX_TO_HIGH:
			*str = "EDSA_EXPARR_INS_INDEX_TO_HIGH";
			break;
		case EDSA_EXPARR_INS_REALLOC_FAIL:
			*str = "EDSA_EXPARR_INS_REALLOC_FAIL";
			break;
		case EDSA_EXPARR_READ_INVALID_INDEX:
			*str = "EDSA_EXPARR_READ_INVALID_INDEX";
			break;
		case EDSA_HEAP_INIT_MALLOC_FAILED:
			*str = "EDSA_HEAP_INIT_MALLOC_FAILED";
			break;
		case EDSA_HEAP_INIT_ZERO_ALLOC_SIZE:
			*str = "EDSA_HEAP_INIT_ZERO_ALLOC_SIZE";
			break;
		case EDSA_HEAP_INIT_MULTIPLICATION_OVERFLOW:
			*str = "EDSA_HEAP_INIT_MULTIPLICATION_OVERFLOW";
			break;
		case EDSA_EXPARR_COPY_INVALID_SRC_INDEX:
			*str = "EDSA_EXPARR_COPY_INVALID_SRC_INDEX";
			break;
		case EDSA_EXPARR_COPY_INVALID_DEST_INDEX:
			*str = "EDSA_EXPARR_COPY_INVALID_DEST_INDEX";
			break;
		case EDSA_EXPARR_COPY_REALLOC_FAIL:
			*str = "EDSA_EXPARR_COPY_REALLOC_FAIL";
			break;
		case EDSA_HEAP_INS_HEAP_FULL:
			*str = "EDSA_HEAP_INS_HEAP_FULL";
			break;
		case EDSA_HEAP_INS_REALLOC_FAIL:
			*str = "EDSA_HEAP_INS_REALLOC_FAIL";
			break;
		case EDSA_HEAP_INS_MALLOC_FAIL:
			*str = "EDSA_HEAP_INS_MALLOC_FAIL";
			break;
		case EDSA_HEAP_REMOVE_MALLOC_FAIL:
			*str = "EDSA_HEAP_REMOVE_MALLOC_FAIL";
			break;
		case EDSA_HEAP_REMOVE_HEAP_EMPTY:
			*str = "EDSA_HEAP_REMOVE_HEAP_EMPTY";
			break;
		case EDSA_HEAP_REPLACE_HEAP_EMPTY:
			*str = "EDSA_HEAP_REPLACE_HEAP_EMPTY";
			break;
		case EDSA_HEAP_REPLACE_MALLOC_FAIL:
			*str = "EDSA_HEAP_REPLACE_MALLOC_FAIL";
			break;
		case EDSA_HEAP_BUILD_REALLOC_FAIL:
			*str = "EDSA_HEAP_BUILD_REALLOC_FAIL";
			break;
		case EDSA_HEAP_BUILD_MALLOC_FAIL:
			*str = "EDSA_HEAP_BUILD_MALLOC_FAIL";
			break;
		case EDSA_HEAP_BUILD_AMOUNT_TO_HIGH:
			*str = "EDSA_HEAP_BUILD_AMOUNT_TO_HIGH";
			break;
		case EDSA_HEAP_CHANGE_CMP_FUNC_MALLOC_FAIL:
			*str = "EDSA_HEAP_CHANGE_CMP_FUNC_MALLOC_FAIL";
			break;
		case EDSA_HTABLE_INIT_MALLOC_FAIL:
			*str = "EDSA_HTABLE_INIT_MALLOC_FAIL";
			break;
		case EDSA_HTABLE_INIT_HTABLE_SIZE_TOO_LARGE:
			*str = "EDSA_HTABLE_INIT_HTABLE_SIZE_TOO_LARGE";
			break;
		case EDSA_HTABLE_INIT_HTABLE_SIZE_ZERO:
			*str = "EDSA_HTABLE_INIT_HTABLE_SIZE_ZERO";
			break;
		case EDSA_HTABLE_INIT_REALLOC_FAIL:
			*str = "EDSA_HTABLE_INIT_REALLOC_FAIL";
			break;
		case EDSA_HTABLE_INS_HTABLE_TOO_LARGE:
			*str = "EDSA_HTABLE_INS_HTABLE_TOO_LARGE";
			break;
		case EDSA_HTABLE_INS_MALLOC_FAIL:
			*str = "EDSA_HTABLE_INS_MALLOC_FAIL";
			break;
		case EDSA_HTABLE_INS_REALLOC_FAIL:
			*str = "EDSA_HTABLE_INS_REALLOC_FAIL";
			break;
		default:
			*str = "UNKNOWN_ERROR";
			break;

	}

	return EDSA_SUCCESS;
}
